---
title: Practice Activity 3.2
author: Sam Ricafrente
format:
    html:
        toc: true
        code-fold: true
        embed-resources: true
---

0. Load the `penguins` dataset from the `palmerpenguins` library, as well as any other libraries you need.

In [1]:
# !pip install palmerpenguins

Collecting palmerpenguins
  Downloading palmerpenguins-0.1.4-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from palmerpenguins) (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from palmerpenguins) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->palmerpenguins) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->palmerpenguins) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->palmerpenguins) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->palmerpenguins) (1.16.0)
Downloading palmerpenguins-0.1.4-py3-none-any.whl (17 kB)
Installing collected packages: palmerpenguins
Successfully installed palmerpenguins-0.1.4

In [35]:
import pandas as pd
from palmerpenguins import load_penguins

# Load the penguins dataset
penguins = load_penguins()

penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007

1. Write a function that takes in information about a penguin, and returns one of the following definitions:

*   "Big Mouth Billy": Male penguins with bill length times bill depth greater than 800.
*   "Dainty Daisy": Female penguins with flipper length less than 5% of body mass.
*   "Average Adelie:" Any Adelie penguins that do not fall into either category.
*   "Other": Any penguins that do not fall into any of the categories.

In [28]:
def classify_penguins(bill_length, bill_depth, body_mass, flipper_length, sex, species):
    if sex == "male" and bill_length * bill_depth > 800:
        return "Big Mouth Billy"
    elif sex == "female" and flipper_length < 0.05 * body_mass:
        return "Dainty Daisy"
    elif species == "Adelie" and bill_length * bill_depth < 800 and flipper_length > 0.05 * body_mass:
        return "Average Adelie"
    else:
        return "Other"

2. Use an iterable function to create a new variable called `category_name` that adds these labels.

In [36]:
# Apply the classification using a lambda function and create the category_name column
penguins['category_name'] = penguins.apply(
    lambda row: classify_penguins(row['bill_length_mm'], row['bill_depth_mm'], row['body_mass_g'],
                                  row['flipper_length_mm'], row['sex'], row['species']), axis=1)

# Display the first few rows to verify
penguins.head(10)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,category_name
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007,Other
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007,Dainty Daisy
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007,Average Adelie
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007,Other
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007,Average Adelie
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,male,2007,Big Mouth Billy
6,Adelie,Torgersen,38.9,17.8,181.0,3625.0,female,2007,Dainty Daisy
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,male,2007,Other
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN,2007,Average Adelie
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN,2007,Other

3. Run the following code to find the counts for each type.

In [37]:
penguins.value_counts("category_name")

category_name
Other              126
Average Adelie      85
Big Mouth Billy     71
Dainty Daisy        62
Name: count, dtype: int64